services:

  assessment:
    build:
      context: .
      dockerfile: ./assessment-service/Dockerfile
    container_name: assessment-service
    depends_on:
      kafka:
        condition: service_started
      assessment-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: jdbc:postgresql://assessment-db:5432/assessment
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8091:8080"

  claims:
    build:
      context: .
      dockerfile: ./claims-service/Dockerfile
    container_name: claims-service
    depends_on:
      kafka:
        condition: service_started
      claim-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: jdbc:postgresql://claim-db:5432/claim
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8092:8080"

  payment:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    depends_on:
      kafka:
        condition: service_started
      payment-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: jdbc:postgresql://payment-db:5432/payment
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8093:8080"

  assessment-db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: assessment
    volumes:
      - ./docker/volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d assessment" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  claim-db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: claim
    volumes:
      - ./docker/volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d claim" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  payment-db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: payment
    volumes:
      - ./docker/volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d payment" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  kafka:
    image: apache/kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1