spring:
  application:
    name: PaymentApp

  datasource:
    url: ${DB_URL:jdbc:postgresql://payment-db:5432/payment}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: liquibase

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    consumer:
      group-id: payment-service