spring:

  application:
    name: AssessmentApp

  datasource:
    url: ${DB_URL:jdbc:postgresql://assessment-db:5432/assessment}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: liquibase

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    consumer:
      group-id: assessment-service