spring:

  application:
    name: AssessmentApp

  datasource:
    url: ${DB_URL:jdbc:postgresql://assessment-db:5432/assessment}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}