spring:

  application:
    name: ClaimsApp

  datasource:
    url: ${DB_URL:jdbc:postgresql://claims-db:5432/claim}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: liquibase
    default-schema: claim

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: claim

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
